package com.reconcileguard.domain;

public enum IssueType {
    CUSTOMER_DEBITED_PAYMENT_FAILED,
    BENEFICIARY_CREDIT_PENDING,
    GATEWAY_TIMEOUT_WITHOUT_FINAL_STATUS,
    DUPLICATE_UTR_REFERENCE,
    SLA_BREACH_RISK
}
