-- ReconcileGuard Oracle schema and PL/SQL reconciliation package.
-- The Spring Boot app runs locally with H2/Flyway; this file shows how the
-- same domain model maps to an Oracle-backed banking deployment.

CREATE TABLE rg_payment_txn (
    txn_id              VARCHAR2(40) PRIMARY KEY,
    channel             VARCHAR2(20) NOT NULL,
    utr                 VARCHAR2(60) NOT NULL,
    customer_name       VARCHAR2(120) NOT NULL,
    branch              VARCHAR2(80) NOT NULL,
    amount              NUMBER(14,2) NOT NULL,
    initiated_at        TIMESTAMP NOT NULL,
    cbs_status          VARCHAR2(20) NOT NULL,
    switch_status       VARCHAR2(20) NOT NULL,
    gateway_status      VARCHAR2(20) NOT NULL,
    complaint_flag      CHAR(1) DEFAULT 'N' CHECK (complaint_flag IN ('Y','N')),
    risk_score          NUMBER(3) DEFAULT 0,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE rg_recon_case (
    case_id             VARCHAR2(40) PRIMARY KEY,
    txn_id              VARCHAR2(40) NOT NULL REFERENCES rg_payment_txn(txn_id),
    issue_type          VARCHAR2(80) NOT NULL,
    severity            VARCHAR2(20) NOT NULL,
    status              VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    sla_hours           NUMBER(4) NOT NULL,
    root_cause          VARCHAR2(500) NOT NULL,
    recommended_action  VARCHAR2(500) NOT NULL,
    owner_queue         VARCHAR2(120) NOT NULL,
    resolution_note     VARCHAR2(500),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_rg_case UNIQUE (txn_id, issue_type)
);

CREATE TABLE rg_recon_audit (
    audit_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time          TIMESTAMP DEFAULT SYSTIMESTAMP,
    actor               VARCHAR2(120) NOT NULL,
    action              VARCHAR2(80) NOT NULL,
    reference_id        VARCHAR2(60) NOT NULL,
    details             VARCHAR2(800)
);

CREATE INDEX idx_rg_txn_channel_status ON rg_payment_txn(channel, cbs_status, switch_status);
CREATE INDEX idx_rg_txn_utr ON rg_payment_txn(utr);
CREATE INDEX idx_rg_case_status_sev ON rg_recon_case(status, severity);
CREATE INDEX idx_rg_case_txn ON rg_recon_case(txn_id);

CREATE OR REPLACE PACKAGE rg_recon_pkg AS
    PROCEDURE run_reconciliation(p_actor IN VARCHAR2);
    PROCEDURE resolve_case(
        p_case_id IN VARCHAR2,
        p_actor IN VARCHAR2,
        p_resolution_note IN VARCHAR2
    );
END rg_recon_pkg;
/

CREATE OR REPLACE PACKAGE BODY rg_recon_pkg AS

    PROCEDURE create_case(
        p_txn_id IN VARCHAR2,
        p_issue_type IN VARCHAR2,
        p_severity IN VARCHAR2,
        p_sla_hours IN NUMBER,
        p_root_cause IN VARCHAR2,
        p_action IN VARCHAR2,
        p_owner IN VARCHAR2,
        p_actor IN VARCHAR2
    ) AS
        v_case_id VARCHAR2(40);
    BEGIN
        v_case_id := 'RC-' || SUBSTR(RAWTOHEX(SYS_GUID()), 1, 12);

        INSERT INTO rg_recon_case (
            case_id, txn_id, issue_type, severity, sla_hours,
            root_cause, recommended_action, owner_queue
        )
        VALUES (
            v_case_id, p_txn_id, p_issue_type, p_severity, p_sla_hours,
            p_root_cause, p_action, p_owner
        );

        INSERT INTO rg_recon_audit(actor, action, reference_id, details)
        VALUES (p_actor, 'CASE_CREATED', v_case_id, p_issue_type || ' detected');

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            UPDATE rg_recon_case
               SET root_cause = p_root_cause,
                   recommended_action = p_action,
                   updated_at = SYSTIMESTAMP
             WHERE txn_id = p_txn_id
               AND issue_type = p_issue_type
               AND status <> 'RESOLVED';
    END create_case;

    PROCEDURE run_reconciliation(p_actor IN VARCHAR2) AS
    BEGIN
        FOR r IN (
            SELECT t.*,
                   CASE WHEN COUNT(*) OVER (PARTITION BY utr) > 1 THEN 'Y' ELSE 'N' END duplicate_utr
              FROM rg_payment_txn t
        ) LOOP
            IF r.cbs_status = 'SUCCESS' AND r.switch_status IN ('FAILED', 'REVERSED') THEN
                create_case(
                    r.txn_id,
                    'CUSTOMER_DEBITED_PAYMENT_FAILED',
                    'CRITICAL',
                    4,
                    'Customer debit completed in CBS but switch did not settle successfully.',
                    'Trigger reversal, notify branch, and send customer-safe status update.',
                    'Digital Payments Ops Lead',
                    p_actor
                );
            END IF;

            IF r.cbs_status IN ('PENDING', 'TIMEOUT') AND r.switch_status = 'SUCCESS' THEN
                create_case(
                    r.txn_id,
                    'BENEFICIARY_CREDIT_PENDING',
                    'HIGH',
                    8,
                    'Switch shows success but CBS posting is not complete.',
                    'Verify ledger posting, replay callback, and confirm beneficiary credit.',
                    'Reconciliation Analyst',
                    p_actor
                );
            END IF;

            IF r.gateway_status = 'TIMEOUT' AND SYSTIMESTAMP - r.initiated_at > INTERVAL '2' HOUR THEN
                create_case(
                    r.txn_id,
                    'GATEWAY_TIMEOUT_WITHOUT_FINAL_STATUS',
                    'MEDIUM',
                    12,
                    'Payment gateway timed out and final callback is missing.',
                    'Pull latest gateway status and retry reconciliation.',
                    'Branch Support Queue',
                    p_actor
                );
            END IF;

            IF r.duplicate_utr = 'Y' THEN
                create_case(
                    r.txn_id,
                    'DUPLICATE_UTR_REFERENCE',
                    'HIGH',
                    6,
                    'Same UTR/reference appears on multiple transactions.',
                    'Block duplicate settlement posting and route to maker-checker verification.',
                    'Reconciliation Analyst',
                    p_actor
                );
            END IF;

            IF r.complaint_flag = 'Y'
               AND SYSTIMESTAMP - r.initiated_at > INTERVAL '24' HOUR
               AND r.cbs_status <> 'SUCCESS' THEN
                create_case(
                    r.txn_id,
                    'SLA_BREACH_RISK',
                    'CRITICAL',
                    2,
                    'Customer complaint is open beyond operational SLA and transaction is unresolved.',
                    'Escalate to operations lead and branch support with RCA summary.',
                    'Digital Payments Ops Lead',
                    p_actor
                );
            END IF;
        END LOOP;
    END run_reconciliation;

    PROCEDURE resolve_case(
        p_case_id IN VARCHAR2,
        p_actor IN VARCHAR2,
        p_resolution_note IN VARCHAR2
    ) AS
    BEGIN
        UPDATE rg_recon_case
           SET status = 'RESOLVED',
               resolution_note = p_resolution_note,
               updated_at = SYSTIMESTAMP
         WHERE case_id = p_case_id;

        INSERT INTO rg_recon_audit(actor, action, reference_id, details)
        VALUES (p_actor, 'CASE_RESOLVED', p_case_id, p_resolution_note);
    END resolve_case;

END rg_recon_pkg;
/

-- Useful production-support query for the operations dashboard.
SELECT c.severity,
       t.channel,
       COUNT(*) case_count,
       SUM(t.amount) value_at_risk
  FROM rg_recon_case c
  JOIN rg_payment_txn t ON t.txn_id = c.txn_id
 WHERE c.status = 'OPEN'
 GROUP BY c.severity, t.channel
 ORDER BY CASE c.severity
          WHEN 'CRITICAL' THEN 1
          WHEN 'HIGH' THEN 2
          WHEN 'MEDIUM' THEN 3
          ELSE 4
          END;
