create table rg_payment_txn (
    txn_id varchar(40) not null,
    channel varchar(20) not null,
    utr varchar(60) not null,
    customer_name varchar(120) not null,
    branch varchar(80) not null,
    amount decimal(14, 2) not null,
    initiated_at timestamp not null,
    cbs_status varchar(20) not null,
    switch_status varchar(20) not null,
    gateway_status varchar(20) not null,
    complaint_flag boolean not null,
    risk_score integer not null,
    constraint pk_rg_payment_txn primary key (txn_id)
);

create index idx_rg_payment_channel on rg_payment_txn (channel);
create index idx_rg_payment_utr on rg_payment_txn (utr);
create index idx_rg_payment_status on rg_payment_txn (cbs_status, switch_status, gateway_status);

create table rg_recon_case (
    case_id varchar(40) not null,
    txn_id varchar(40) not null,
    issue_type varchar(80) not null,
    severity varchar(20) not null,
    status varchar(20) not null,
    sla_hours integer not null,
    root_cause varchar(500) not null,
    recommended_action varchar(500) not null,
    owner_queue varchar(120) not null,
    resolution_note varchar(500),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_rg_recon_case primary key (case_id),
    constraint fk_rg_case_txn foreign key (txn_id) references rg_payment_txn (txn_id),
    constraint uq_rg_case unique (txn_id, issue_type)
);

create index idx_rg_case_status on rg_recon_case (status, severity);
create index idx_rg_case_txn on rg_recon_case (txn_id);

create table rg_recon_audit (
    audit_id bigint generated by default as identity primary key,
    event_time timestamp not null,
    actor varchar(120) not null,
    action varchar(80) not null,
    reference_id varchar(60) not null,
    details varchar(800)
);

create index idx_rg_audit_time on rg_recon_audit (event_time);
